import { NextRequest, NextResponse } from 'next/server'
import { redis } from '@/lib/redis'
import { resolveSessionUserId } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { randomUUID } from 'crypto'

// GET /api/alerts/fired — return fired alerts for the user
// Fired alerts are generated by checking alert rules against recent spend data
export async function GET(req: NextRequest) {
  const userId = await resolveSessionUserId(req)
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  try {
    // Load stored fired alerts from Redis
    const raw = await redis.get(`alerts:fired:${userId}`)
    let fired: any[] = []
    if (raw) {
      const parsed = typeof raw === 'string' ? JSON.parse(raw) : raw
      fired = Array.isArray(parsed) ? parsed : []
    }

    // Auto-generate new alerts by checking rules against recent data
    const rulesRaw = await redis.get(`alert_rules:${userId}`)
    const rules: any[] = rulesRaw
      ? (typeof rulesRaw === 'string' ? JSON.parse(rulesRaw) : rulesRaw) ?? []
      : []

    const enabledRules = rules.filter((r: any) => r.enabled)
    if (enabledRules.length > 0) {
      // Get recent spend data
      const now   = new Date()
      const d24h  = new Date(now.getTime() - 24 * 3600000)
      const d48h  = new Date(now.getTime() - 48 * 3600000)

      const [recent, prior] = await Promise.all([
        prisma.decisionLog.aggregate({ where: { userId, createdAt: { gte: d24h } }, _sum: { actualCostMicro: true }, _count: true }),
        prisma.decisionLog.aggregate({ where: { userId, createdAt: { gte: d48h, lt: d24h } }, _sum: { actualCostMicro: true }, _count: true }),
      ])

      const recentCost   = recent._sum.actualCostMicro  ?? 0
      const priorCost    = prior._sum.actualCostMicro   ?? 0
      const recentCount  = recent._count ?? 0
      const priorCount   = prior._count  ?? 0

      const newAlerts: any[] = []

      for (const rule of enabledRules) {
        const alreadyFired = fired.some(
          (f: any) => f.ruleId === rule.id && !f.acknowledged &&
            new Date(f.firedAt).getTime() > now.getTime() - rule.windowMinutes * 60000
        )
        if (alreadyFired) continue

        let triggered = false
        let message   = ''
        let value     = 0

        if (rule.type === 'spend_spike' && priorCost > 0) {
          const pctChange = ((recentCost - priorCost) / priorCost) * 100
          if (pctChange >= rule.threshold) {
            triggered = true
            value     = pctChange
            message   = `Spend increased ${pctChange.toFixed(0)}% in the last ${rule.windowMinutes}min vs prior period. Current: $${(recentCost/1e6).toFixed(4)}, Prior: $${(priorCost/1e6).toFixed(4)}.`
          }
        }

        if (rule.type === 'daily_limit') {
          const dailyCostUsd = recentCost / 1e6
          if (dailyCostUsd >= rule.threshold) {
            triggered = true
            value     = dailyCostUsd
            message   = `Daily spend reached $${dailyCostUsd.toFixed(2)}, exceeding your $${rule.threshold} limit.`
          }
        }

        if (rule.type === 'anomaly' && priorCount > 0) {
          const countChange = ((recentCount - priorCount) / priorCount) * 100
          if (Math.abs(countChange) >= rule.threshold) {
            triggered = true
            value     = countChange
            message   = `Request volume ${countChange > 0 ? 'spiked' : 'dropped'} ${Math.abs(countChange).toFixed(0)}% vs prior period.`
          }
        }

        if (triggered) {
          newAlerts.push({
            id:           randomUUID(),
            ruleId:       rule.id,
            ruleName:     rule.name,
            severity:     rule.type === 'spend_spike' || rule.type === 'daily_limit' ? 'critical' : 'warning',
            message,
            value,
            threshold:    rule.threshold,
            firedAt:      now.toISOString(),
            acknowledged: false,
          })
        }
      }

      if (newAlerts.length > 0) {
        const updated = [...fired, ...newAlerts].slice(-50) // cap at 50
        await redis.setex(`alerts:fired:${userId}`, 86400 * 7, JSON.stringify(updated))
        fired = updated
      }
    }

    return NextResponse.json({ alerts: fired.sort((a, b) => new Date(b.firedAt).getTime() - new Date(a.firedAt).getTime()) })
  } catch (err) {
    console.error('[alerts/fired]', err)
    return NextResponse.json({ alerts: [] })
  }
}
